server:
  port: 8625
  hide_html_extension: true
  domain: "http://localhost:8625"

content:
  language: fr
  header_file: "./source/header.md"
  footer_file: "./source/footer.md"
  theme: "clean"

  blogs: [
    {
      dir: source/blogs/cestoliv
    }
  ]

  podcasts: [
    {
      dir: source/podcasts/cestoliv
    }
  ]